'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.586
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.586.
'
Namespace CloudEmailService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WebService1Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WebService1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private savedToCloudEmailOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Rae.RaeSolutions.My.MySettings.Default.RaeSolutions_CloudEmailService_WebService1
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event savedToCloudEmailCompleted As savedToCloudEmailCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/savedToCloudEmail", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function savedToCloudEmail(ByVal name As String, ByVal releaseNum As String, ByVal repID As String, ByVal repCompany As String, ByVal requestedShipDate As String, ByVal projectRevision As String, ByVal user As String) As Boolean
            Dim results() As Object = Me.Invoke("savedToCloudEmail", New Object() {name, releaseNum, repID, repCompany, requestedShipDate, projectRevision, user})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginsavedToCloudEmail(ByVal name As String, ByVal releaseNum As String, ByVal repID As String, ByVal repCompany As String, ByVal requestedShipDate As String, ByVal projectRevision As String, ByVal user As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("savedToCloudEmail", New Object() {name, releaseNum, repID, repCompany, requestedShipDate, projectRevision, user}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndsavedToCloudEmail(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub savedToCloudEmailAsync(ByVal name As String, ByVal releaseNum As String, ByVal repID As String, ByVal repCompany As String, ByVal requestedShipDate As String, ByVal projectRevision As String, ByVal user As String)
            Me.savedToCloudEmailAsync(name, releaseNum, repID, repCompany, requestedShipDate, projectRevision, user, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub savedToCloudEmailAsync(ByVal name As String, ByVal releaseNum As String, ByVal repID As String, ByVal repCompany As String, ByVal requestedShipDate As String, ByVal projectRevision As String, ByVal user As String, ByVal userState As Object)
            If (Me.savedToCloudEmailOperationCompleted Is Nothing) Then
                Me.savedToCloudEmailOperationCompleted = AddressOf Me.OnsavedToCloudEmailOperationCompleted
            End If
            Me.InvokeAsync("savedToCloudEmail", New Object() {name, releaseNum, repID, repCompany, requestedShipDate, projectRevision, user}, Me.savedToCloudEmailOperationCompleted, userState)
        End Sub
        
        Private Sub OnsavedToCloudEmailOperationCompleted(ByVal arg As Object)
            If (Not (Me.savedToCloudEmailCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent savedToCloudEmailCompleted(Me, New savedToCloudEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub savedToCloudEmailCompletedEventHandler(ByVal sender As Object, ByVal e As savedToCloudEmailCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class savedToCloudEmailCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
