'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Username() As String
            Get
                Return CType(Me("Username"),String)
            End Get
            Set
                Me("Username") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Password() As String
            Get
                Return CType(Me("Password"),String)
            End Get
            Set
                Me("Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property RememberLogin() As Boolean
            Get
                Return CType(Me("RememberLogin"),Boolean)
            End Get
            Set
                Me("RememberLogin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Division() As String
            Get
                Return CType(Me("Division"),String)
            End Get
            Set
                Me("Division") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("doc")>  _
        Public Property ExportExtension() As String
            Get
                Return CType(Me("ExportExtension"),String)
            End Get
            Set
                Me("ExportExtension") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.rae-corp.com/CASEYJ/WebServices/RAESolutionsLogWS/RAESolutionsLog.asmx"& _ 
            "")>  _
        Public ReadOnly Property RAESolutionsLog() As String
            Get
                Return CType(Me("RAESolutionsLog"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property IsSettingsUpgradeRequired() As Boolean
            Get
                Return CType(Me("IsSettingsUpgradeRequired"),Boolean)
            End Get
            Set
                Me("IsSettingsUpgradeRequired") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\Drawings\Databases\D"& _ 
            "rawingData.mdb;Persist Security Info=True")>  _
        Public ReadOnly Property DrawingDataConnectionString() As String
            Get
                Return CType(Me("DrawingDataConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsDrawingInstalled() As Boolean
            Get
                Return CType(Me("IsDrawingInstalled"),Boolean)
            End Get
            Set
                Me("IsDrawingInstalled") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\Databases\FluidCoole"& _ 
            "r.mdb;Persist Security Info=True")>  _
        Public ReadOnly Property FluidCoolerConnectionString() As String
            Get
                Return CType(Me("FluidCoolerConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.rae-corp.com/CASEYJ/WebServices/RAESolutionsLogWS/RAESolutionsLog.asmx"& _ 
            "")>  _
        Public ReadOnly Property RaeSolutions_com_rae_corp_www_RAESolutionsLog() As String
            Get
                Return CType(Me("RaeSolutions_com_rae_corp_www_RAESolutionsLog"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BackupLocation() As String
            Get
                Return CType(Me("BackupLocation"),String)
            End Get
            Set
                Me("BackupLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BackupDate() As Date
            Get
                Return CType(Me("BackupDate"),Date)
            End Get
            Set
                Me("BackupDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowTipOnStartup() As Boolean
            Get
                Return CType(Me("ShowTipOnStartup"),Boolean)
            End Get
            Set
                Me("ShowTipOnStartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property MaxOSMajorVersionCheck() As Integer
            Get
                Return CType(Me("MaxOSMajorVersionCheck"),Integer)
            End Get
            Set
                Me("MaxOSMajorVersionCheck") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=\\fileserver1\fileser1_e\rae data\database\tools.mdb; Provider=Micros"& _ 
            "oft.Jet.OleDb.4.0;")>  _
        Public ReadOnly Property CustomMultipliers() As String
            Get
                Return CType(Me("CustomMultipliers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.\UserNamePassword_Encrypted.mdb; Provider=Microsoft.Jet.OleDb.4.0;")>  _
        Public ReadOnly Property Identities() As String
            Get
                Return CType(Me("Identities"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.\CompressorData.mdb; Provider=Microsoft.Jet.OleDb.4.0;")>  _
        Public ReadOnly Property CompressorRepo() As String
            Get
                Return CType(Me("CompressorRepo"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.\20a0capacitiesDEC17.mdb; Provider=Microsoft.Jet.OleDb.4.0;")>  _
        Public ReadOnly Property CondensingUnitRepo() As String
            Get
                Return CType(Me("CondensingUnitRepo"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\data\boxload2.mdb;Pe"& _ 
            "rsist Security Info=True")>  _
        Public ReadOnly Property boxload2ConnectionString() As String
            Get
                Return CType(Me("boxload2ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://apps.util.rae-corp.net/ttphelp/raesolutionsonline/OrderPlacement/TransferF"& _ 
            "ile.asmx")>  _
        Public ReadOnly Property RaeSolutions_OrderPlacementWS_TransferFile() As String
            Get
                Return CType(Me("RaeSolutions_OrderPlacementWS_TransferFile"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CustomDataFilePath() As String
            Get
                Return CType(Me("CustomDataFilePath"),String)
            End Get
            Set
                Me("CustomDataFilePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://service.raecloud.com/raesolutionsonline2020/cloudsaving/cloudsave.asmx")>  _
        Public ReadOnly Property RaeSolutions_CloudSaveService_CloudSave() As String
            Get
                Return CType(Me("RaeSolutions_CloudSaveService_CloudSave"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://service.raecloud.com/raesolutionswebservices/CloudEmail.asmx")>  _
        Public ReadOnly Property RaeSolutions_CloudEmailService_WebService1() As String
            Get
                Return CType(Me("RaeSolutions_CloudEmailService_WebService1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://service.raecloud.com/raesolutionsonline/webservices/authenticate.asmx")>  _
        Public ReadOnly Property RaeSolutions_IsContractor_Authenticate() As String
            Get
                Return CType(Me("RaeSolutions_IsContractor_Authenticate"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Rae.RaeSolutions.My.MySettings
            Get
                Return Global.Rae.RaeSolutions.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
