Namespace rae.solutions.condensing_units

    Class Table
        Public Const table_name As String = "Table5"
        Public Const model As String = "Model"
        Public Const subcooling_percent_1 As String = "Degrees_sub_cooling_Coil_1"
        Public Const subcooling_percent_2 As String = "Degrees_sub_cooling_Coil_2"
        Public Const authorization_level As String = "Rev_Level"
        Public Const division As String = "Company"
        Public Const capacity_min As String = "Approx_Min_Cap"
        Public Const capacity_max As String = "Approx_Max_Cap"
        Public Const minSuctionOfUnit As String = "Min_suction"
        Public Const maxSuctionOfUnit As String = "Max_suction"
        Public Const temperature_range As String = "Temperature_Range"
        Public Const series As String = "Unit_Series"

        Public Const suction_connection_ods_1 As String = "SuctionConnectionODS1"
        Public Const liquid_connection_ods_1 As String = "LiquidConnectionODS1"
        Public Const single_circuit_suction_connection_ods As String = "SingleCircuitSuctionConnectionODS"
        Public Const single_circuit_liquid_connection_ods As String = "SingleCircuitLiquidConnectionODS"
        Public Const single_phase_motor_part_number As String = "1_ph_mtr_part_number"
        Public Const three_phase_motor_part_number230460 As String = "3_ph_mtr_part_number"
        Public Const three_phase_motor_part_number575 As String = "3_ph_575V_mtr_part_number"
        Public Const compressor_type_1 As String = "Compressor_Type_1"
        Public Const compressor_quantity_description As String = "Compressor_Qty_Desc"
        Public Const number_of_circuits As String = "Circuits_Per_Unit"
        Public Const has_subcooling_1 As String = "Subcooling_1"
        Public Const number_of_refrigerant_circuits_1 As String = "Number_Ref_Circuits_1"
        Public Const compressor_quantity_1 As String = "Compr_Qty_1"
        Public Const CompressorMasterID1 As String = "CompressorMasterID1"
       ' Public Const compressorManuModel1 As String = "ManufacturerModelNumber1"
        'Public Const compressor_file_1 As String = "Comprfile_1"
        Public Const refrigerant As String = "Refg_1"
        Public Const coil_diameter_1 As String = "Coil_Dia_1"
        'Public Const fan_diameter_1 As String = "Fan_Dia_1"
        Public Const fanID_1 As String = "FanID_1"
        Public Const fan_quantity_1 As String = "FanQty_1"
        Public Const fan_hp_1 As String = "FanHp_1"
        Public Const fanRPM_1 As String = "FanRPM_1"
        Public Const coil_model_1 As String = "Coil_1"
        Public Const coil_quantity_1 As String = "CoilQty_1"
        Public Const coil_height_1 As String = "Coil_H_1"
        Public Const coil_length_1 As String = "Coil_L_1"
        Public Const number_of_rows_1 As String = "Rows_1"
        Public Const fpi_1 As String = "FPI_1"
        Public Const capacity_1 As String = "Cap_1"

        Public Const suction_connection_ods_2 As String = "SuctionConnectionODS2"
        Public Const liquid_connection_ods_2 As String = "LiquidConnectionODS2"
        Public Const compressor_type_2 As String = "Compressor_Type_2"
        Public Const has_subcooling_2 As String = "Subcooling_2"
        Public Const number_of_refrigerant_circuits_2 As String = "Number_Ref_Circuits_2"
        Public Const compressor_quantity_2 As String = "Compr_Qty_2"
        Public Const CompressorMasterID2 As String = "CompressorMasterID2"

        '  Public Const compressorManuModel2 As String = "ManufacturerModelNumber2"
        'Public Const compressor_file_2 As String = "Comprfile_2"
        Public Const refrigerant_2 As String = "Refg_2"
        Public Const coil_diameter_2 As String = "Coil_Dia_2"
        '        Public Const fan_diameter_2 As String = "Fan_Dia_2"
        Public Const fanID_2 As String = "FanID_2"
        Public Const fan_quantity_2 As String = "FanQty_2"
        Public Const fan_hp_2 As String = "FanHp_2"
        Public Const fanRPM_2 As String = "FanRPM_2"

        Public Const coil_model_2 As String = "Coil_2"
        Public Const coil_quantity_2 As String = "CoilQty_2"
        Public Const coil_height_2 As String = "Coil_H_2"
        Public Const coil_length_2 As String = "Coil_L_2"
        Public Const number_of_rows_2 As String = "Rows_2"
        Public Const fpi_2 As String = "FPI_2"
        Public Const capacity_2 As String = "Cap_2"

        Public Const dimensions As String = "Dimensions"
        Public Const mca_208 As String = "MCA_208"
        Public Const mca_460 As String = "MCA_460"
        Public Const operating_weight As String = "Operating_Weight"
        Public Const shipping_weight As String = "Shipping_Weight"
        Public Const flood_operating_charge As String = "Flood_op_charge"
        Public Const receiver_size As String = "Rec_size"
        Public Const receiver_capacity_at_80_percent As String = "Rec_cap_80%"
        Public Const standard_operating_charge As String = "Std_op_charge"
        Public Const dimension_a As String = "Dim_A"
        Public Const dimension_b As String = "Dim_B"
        Public Const dimension_c As String = "Dim_C"
        Public Const dimension_d As String = "Dim_D"
        Public Const unit_length As String = "Unit_length"
        Public Const unit_width As String = "Unit_width"
        Public Const unit_height As String = "Unit_height"

        Public Const CoilID_1 As String = "CoilID_1"
        Public Const CoilID_2 As String = "CoilID_2"

        Public Const ConstantReturnGasTemp As String = "constantReturnGasTemp"

    End Class

End Namespace
