Namespace Rae.RaeSolutions.DataAccess.Projects.Tables

    Public Class CondensingUnitProcessTable

        Public Shared ReadOnly TableName As String = "CondensingUnitProcesses"
        Public Shared ReadOnly ProcessID As String = "ProcessID"
        Public Shared ReadOnly Revision As String = "Revision"
        Public Shared ReadOnly RevisionDate As String = "RevisionDate"
        Public Shared ReadOnly ProjectRevision As String = "ProjectRevision"
        Public Shared ReadOnly ProcessRevisionDescription As String = "ProcessRevisionDescription"
        Public Shared ReadOnly CreatedBy As String = "CreatedBy"
        Public Shared ReadOnly Version As String = "Version"
        Public Shared ReadOnly Notes As String = "Notes"
        Public Shared ReadOnly Name As String = "Name"
        Public Shared ReadOnly CondensingUnitSeries As String = "CondensingUnitSeries"
        Public Shared ReadOnly Capacity As String = "Capacity"
        Public Shared ReadOnly RunTimeAdjust As String = "RunTimeAdjust"
        Public Shared ReadOnly CondensingUnitsRequired As String = "CondensingUnitsRequired"
        Public Shared ReadOnly RunTime As String = "RunTime"
        Public Shared ReadOnly AmbientTemperature As String = "AmbientTemperature"
        Public Shared ReadOnly SuctionTemperature As String = "SuctionTemperature"
        Public Shared ReadOnly Refrigerant As String = "Refrigerant"
        Public Shared ReadOnly Compressor As String = "Compressor"
        Public Shared ReadOnly CompressorPerUnit As String = "CompressorPerUnit"
        Public Shared ReadOnly CircuitsPerUnit As String = "CircuitsPerUnit"
        Public Shared ReadOnly Altitude As String = "Altitude"
        Public Shared ReadOnly RunType As String = "RunType"
        Public Shared ReadOnly NoCondensingUnits As String = "NoCondensingUnits"
        Public Shared ReadOnly CondensingUnitModel As String = "CondensingUnitModel"
        Public Shared ReadOnly CustomCondensingUnitModel As String = "CustomCondensingUnitModel"
        Public Shared ReadOnly RatingAmbient As String = "RatingAmbient"
        Public Shared ReadOnly RatingAmbientInterval As String = "RatingAmbientInterval"
        Public Shared ReadOnly RatingAmbientStep As String = "RatingAmbientStep"
        Public Shared ReadOnly RatingSuction As String = "RatingSuction"
        Public Shared ReadOnly RatingSuctionInterval As String = "RatingSuctionInterval"
        Public Shared ReadOnly RatingSuctionStep As String = "RatingSuctionStep"
        Public Shared ReadOnly RatingRefrigerant As String = "RatingRefrigerant"
        Public Shared ReadOnly RatingAltitude As String = "RatingAltitude"
        Public Shared ReadOnly RatingSubCooling As String = "RatingSubCooling"
        Public Shared ReadOnly RatingCatalog As String = "RatingCatalog"
        Public Shared ReadOnly RatingHertz As String = "RatingHertz"
        Public Shared ReadOnly RatingSafety As String = "RatingSafety"
        Public Shared ReadOnly Compressor1 As String = "Compressor1"
        Public Shared ReadOnly Compressor2 As String = "Compressor2"
        Public Shared ReadOnly Compressor3 As String = "Compressor3"
        Public Shared ReadOnly Compressor4 As String = "Compressor4"
        Public Shared ReadOnly CompressorQuantity1 As String = "CompressorQuantity1"
        Public Shared ReadOnly CompressorQuantity2 As String = "CompressorQuantity2"
        Public Shared ReadOnly CompressorQuantity3 As String = "CompressorQuantity3"
        Public Shared ReadOnly CompressorQuantity4 As String = "CompressorQuantity4"
        Public Shared ReadOnly FinHeight1 As String = "FinHeight1"
        Public Shared ReadOnly FinHeight2 As String = "FinHeight2"
        Public Shared ReadOnly FinHeight3 As String = "FinHeight3"
        Public Shared ReadOnly FinHeight4 As String = "FinHeight4"
        Public Shared ReadOnly CoilRows1 As String = "CoilRows1"
        Public Shared ReadOnly CoilRows2 As String = "CoilRows2"
        Public Shared ReadOnly CoilRows3 As String = "CoilRows3"
        Public Shared ReadOnly CoilRows4 As String = "CoilRows4"
        Public Shared ReadOnly CoilFinWidth1 As String = "CoilFinWidth1"
        Public Shared ReadOnly CoilFinWidth2 As String = "CoilFinWidth2"
        Public Shared ReadOnly CoilFinWidth3 As String = "CoilFinWidth3"
        Public Shared ReadOnly CoilFinWidth4 As String = "CoilFinWidth4"
        Public Shared ReadOnly CoilSubCoolingPercentage1 As String = "CoilSubCoolingPercentage1"
        Public Shared ReadOnly CoilSubCoolingPercentage2 As String = "CoilSubCoolingPercentage2"
        Public Shared ReadOnly CoilSubCoolingPercentage3 As String = "CoilSubCoolingPercentage3"
        Public Shared ReadOnly CoilSubCoolingPercentage4 As String = "CoilSubCoolingPercentage4"
        Public Shared ReadOnly FinsPerInch1 As String = "FinsPerInch1"
        Public Shared ReadOnly FinsPerInch2 As String = "FinsPerInch2"
        Public Shared ReadOnly FinsPerInch3 As String = "FinsPerInch3"
        Public Shared ReadOnly FinsPerInch4 As String = "FinsPerInch4"
        Public Shared ReadOnly FanDia1 As String = "FanDia1"
        Public Shared ReadOnly FanDia2 As String = "FanDia2"
        Public Shared ReadOnly FanDia3 As String = "FanDia3"
        Public Shared ReadOnly FanDia4 As String = "FanDia4"
        Public Shared ReadOnly FanQuantity1 As String = "FanQuantity1"
        Public Shared ReadOnly FanQuantity2 As String = "FanQuantity2"
        Public Shared ReadOnly FanQuantity3 As String = "FanQuantity3"
        Public Shared ReadOnly FanQuantity4 As String = "FanQuantity4"
        Public Shared ReadOnly Division As String = "Division"
        Public Shared ReadOnly Use10Coefficients As String = "Use10Coefficients"
        Public Shared ReadOnly Voltage As String = "Voltage"

        Public Shared ReadOnly TubeDiameter1 As String = "TubeDiameter1"
        Public Shared ReadOnly TubeDiameter2 As String = "TubeDiameter2"
        Public Shared ReadOnly TubeDiameter3 As String = "TubeDiameter3"
        Public Shared ReadOnly TubeDiameter4 As String = "TubeDiameter4"

        Public Shared ReadOnly TubeSurface1 As String = "TubeSurface1"
        Public Shared ReadOnly TubeSurface2 As String = "TubeSurface2"
        Public Shared ReadOnly TubeSurface3 As String = "TubeSurface3"
        Public Shared ReadOnly TubeSurface4 As String = "TubeSurface4"

        Public Shared ReadOnly FinType1 As String = "FinType1"
        Public Shared ReadOnly FinType2 As String = "FinType2"
        Public Shared ReadOnly FinType3 As String = "FinType3"
        Public Shared ReadOnly FinType4 As String = "FinType4"

        Public Shared ReadOnly FanRPM1 As String = "FanRPM1"
        Public Shared ReadOnly FanRPM2 As String = "FanRPM2"
        Public Shared ReadOnly FanRPM3 As String = "FanRPM3"
        Public Shared ReadOnly FanRPM4 As String = "FanRPM4"

        Public Shared ReadOnly DOEModel As String = "DOEModel"


    End Class

End Namespace
