Namespace Rae.RaeSolutions.DataAccess.Projects.Tables

   Public Class WCChillerProcessTable
      Public Shared ReadOnly TableName As String = "WCChillerProcesses"
      Public Shared ReadOnly ID As String = "ID"
      Public Shared ReadOnly ProcessId As String = "ProcessId"
      Public Shared ReadOnly Revision As String = "Revision"
      Public Shared ReadOnly RevisionDate As String = "RevisionDate"
      Public Shared ReadOnly ProjectRevision As String = "ProjectRevision"
      Public Shared ReadOnly ProcessRevisionDescription As String = "ProcessRevisionDescription"
      Public Shared ReadOnly CreatedBy As String = "CreatedBy"
      Public Shared ReadOnly Version As String = "Version"
      Public Shared ReadOnly Notes As String = "Notes"
      Public Shared ReadOnly Name As String = "Name"
      Public Shared ReadOnly Series As String = "Series"
      Public Shared ReadOnly NewCoefficients As String = "NewCoefficients"
      Public Shared ReadOnly Model As String = "Model"
      Public Shared ReadOnly ModelDesc As String = "ModelDesc"
      Public Shared ReadOnly Fluid As String = "Fluid"
      Public Shared ReadOnly GlycolPercentage As String = "GlycolPercentage"
      Public Shared ReadOnly CoolingMedia As String = "CoolingMedia"
      Public Shared ReadOnly SpecificHeat As String = "SpecificHeat"
      Public Shared ReadOnly SpecificGravity As String = "SpecificGravity"
      Public Shared ReadOnly SubCooling As String = "SubCooling"
      Public Shared ReadOnly Refrigerant As String = "Refrigerant"
      Public Shared ReadOnly TempRange As String = "TempRange"
      Public Shared ReadOnly AmbientTemp As String = "AmbientTemp"
      Public Shared ReadOnly LeavingFluidTemp As String = "LeavingFluidTemp"
      Public Shared ReadOnly System As String = "System"
      Public Shared ReadOnly Hertz As String = "Hertz"
      Public Shared ReadOnly Volts As String = "Volts"
      Public Shared ReadOnly Approach As String = "Approach"
      Public Shared ReadOnly SafetyOverride As String = "SafetyOverride"
      Public Shared ReadOnly Circuit1 As String = "Circuit1"
      Public Shared ReadOnly Circuit2 As String = "Circuit2"
      Public Shared ReadOnly NumCompressors1 As String = "NumCompressors1"
      Public Shared ReadOnly NumCompressors2 As String = "NumCompressors2"
      Public Shared ReadOnly Compressors1 As String = "Compressors1"
      Public Shared ReadOnly Compressors2 As String = "Compressors2"

      'condenser section will probably change
      Public Shared ReadOnly NumCoils1 As String = "NumCoils1"
      Public Shared ReadOnly NumCoils2 As String = "NumCoils2"
      Public Shared ReadOnly Condenser1 As String = "Condenser1"
      Public Shared ReadOnly Condenser2 As String = "Condenser2"
      Public Shared ReadOnly DischargeLineLoss As String = "DischargeLineLoss"
      Public Shared ReadOnly SuctionLineLoss As String = "SuctionLineLoss"
      Public Shared ReadOnly Altitude As String = "Altitude"
      Public Shared ReadOnly PumpWatts As String = "PumpWatts"
      Public Shared ReadOnly FanWatts As String = "FanWatts"
      Public Shared ReadOnly CondenserCapacity1 As String = "CondenserCapacity1"
      Public Shared ReadOnly CondenserCapacity2 As String = "CondenserCapacity2"

      Public Shared ReadOnly EvaporatorModel As String = "EvaporatorModel"
      Public Shared ReadOnly EvaporatorModelDesc As String = "EvaporatorModelDesc"
      Public Shared ReadOnly NumEvap As String = "NumEvap"
      Public Shared ReadOnly FoulingFactor As String = "FoulingFactor"
      Public Shared ReadOnly CapacityType As String = "CapacityType"
      Public Shared ReadOnly EvaporatorCapacity As String = "EvaporatorCapacity"
      Public Shared ReadOnly CatalogRating As String = "CatalogRating"
      Public Shared ReadOnly ApproachRange As String = "ApproachRange"
      Public Shared ReadOnly Evap8Degr1 As String = "Evap8Degr1"
      Public Shared ReadOnly Evap8Degr2 As String = "Evap8Degr2"
      Public Shared ReadOnly Evap10Degr1 As String = "Evap10Degr1"
      Public Shared ReadOnly Evap10Degr2 As String = "Evap10Degr2"

      Public Shared ReadOnly Division As String = "Division"

   End Class

End Namespace