Imports Rae.Data.Refactoring
Imports Rae.Data.MicrosoftAccess


Public Class CoolStuffAddTables
    Inherits RefactoringBase

    Public Sub New(ByVal connectionString As String)
        connectionString_ = connectionString


    End Sub


    Public Overrides ReadOnly Property Description() As String
        Get
            Return "Adds COOL STUFF Tables to Projects database."
        End Get
    End Property

    Protected Overrides Sub Refactor()
        Dim commands As New Commands(Me.ConnectionString)
        commands.AddTable("CoolStuffProjects")
        commands.AddColumn("CoolStuffProjects", New Column("ID", New DataTypes.AutoNumber))
        commands.AddColumn("CoolStuffProjects", New Column("PROJECTID", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("REVISION", New DataTypes.LongInteger))
        commands.AddColumn("CoolStuffProjects", New Column("Ambient", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ExtWB", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("RmTemp", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("RMWB", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("roomVolume", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("roomArea", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("Height", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ExtTempW1", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ExtTempW2", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ExtTempW3", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ExtTempW4", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ExtTempW5", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ExtTempW6", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("InsulW1", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("InsulW2", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("InsulW3", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("InsulW4", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("InsulW5", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("InsulW6", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ThickW1", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ThickW2", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ThickW3", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ThickW4", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ThickW5", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ThickW6", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("KFactorW1", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("KFactorW2", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("KFactorW3", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("KFactorW4", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("KFactorW5", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("KFactorW6", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("Walltot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("FExtTemp", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("InsulF", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ThickF", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("KFactorF", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("FloorTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("CExtTemp", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("InsulC", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ThickC", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("KFactorC", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("CeilingTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("TransTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("IVolume", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("InfWB", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("InfDB", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("IFactor", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("IAirChg", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("IHeatRem", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("TotInfil", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("Product", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("Type", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("FreezePt", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("CHeat", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("CFHeat", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("FLatent", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("CIbs", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("CLoad", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("CPull", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("CEnter", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("CFinal", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("CTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("FTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("CFPTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("CFTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("RIbs", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("RHeat", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("RTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("ProdTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("WattL", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("TotOL", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("MotorHP", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("TotOM", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("People", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("TotOP", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("OtherType", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("OtherBTU", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("TotOO", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("OtherTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("SumTran", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("SumINf", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("SumProd", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("SumOther", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("SumTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("Safety", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("SafetyTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("RunVar", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("RunVarTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("LoadTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("btnAllWallsy", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffProjects", New Column("btnallwallsN", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffProjects", New Column("chkFreezept", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffProjects", New Column("chkfreezetoCore", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffProjects", New Column("mystate", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("mycity", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("rw1", New DataTypes.Single))
        commands.AddColumn("CoolStuffProjects", New Column("rw2", New DataTypes.Single))
        commands.AddColumn("CoolStuffProjects", New Column("rw3", New DataTypes.Single))
        commands.AddColumn("CoolStuffProjects", New Column("rw4", New DataTypes.Single))
        commands.AddColumn("CoolStuffProjects", New Column("rw5", New DataTypes.Single))
        commands.AddColumn("CoolStuffProjects", New Column("rw6", New DataTypes.Single))
        commands.AddColumn("CoolStuffProjects", New Column("rwfloor", New DataTypes.Single))
        commands.AddColumn("CoolStuffProjects", New Column("rwceiling", New DataTypes.Single))
        commands.AddColumn("CoolStuffProjects", New Column("kfactors", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffProjects", New Column("forklift", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("totforklift", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("dockdoors", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("totdockdoors", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("wall1", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("wall2", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("wall3", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("wall4", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("wall5", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("wall6", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("height1", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("height2", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("height3", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("height4", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("height5", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("height6", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("rdorectangle", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffProjects", New Column("txtimagecounter", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("Description", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("UserCapacity", New DataTypes.Text))
        commands.AddColumn("CoolStuffProjects", New Column("UserCapacityChecked", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffProjects", New Column("CreatedWhen", New DataTypes.DateTime))
        commands.AddColumn("CoolStuffProjects", New Column("RoomNumber", New DataTypes.Text))
        ' commands.AddColumn("CoolStuffProjects", New Column("BLName", New DataTypes.Text))
        ' commands.AddColumn("CoolStuffProjects", New Column("ProcessID", New DataTypes.Text))

        commands.AddTable("CoolStuffPreferences")
        commands.AddColumn("CoolStuffPreferences", New Column("Contact", New DataTypes.Text))
        commands.AddColumn("CoolStuffPreferences", New Column("Addr1", New DataTypes.Text))
        commands.AddColumn("CoolStuffPreferences", New Column("Addr2", New DataTypes.Text))
        commands.AddColumn("CoolStuffPreferences", New Column("City", New DataTypes.Text))
        commands.AddColumn("CoolStuffPreferences", New Column("State", New DataTypes.Text))
        commands.AddColumn("CoolStuffPreferences", New Column("Zip", New DataTypes.Text))
        commands.AddColumn("CoolStuffPreferences", New Column("Phone", New DataTypes.Text))
        commands.AddColumn("CoolStuffPreferences", New Column("Fax", New DataTypes.Text))
        commands.AddColumn("CoolStuffPreferences", New Column("Email", New DataTypes.Text))
        commands.AddColumn("CoolStuffPreferences", New Column("mycounter", New DataTypes.AutoNumber))
        commands.AddColumn("CoolStuffPreferences", New Column("MyDefaultState", New DataTypes.Text))
        commands.AddColumn("CoolStuffPreferences", New Column("MyDefaultCity", New DataTypes.Text))


        commands.AddTable("CoolStuffProductSelections")
        commands.AddColumn("CoolStuffProductSelections", New Column("ID", New DataTypes.AutoNumber))
        commands.AddColumn("CoolStuffProductSelections", New Column("ProjectID", New DataTypes.LongInteger))
        commands.AddColumn("CoolStuffProductSelections", New Column("Product", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("Type", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("FreezePt", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("CHeat", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("CFHeat", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("FLatent", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("CIbs", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("CLoad", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("CPull", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("CEnter", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("CFinal", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("CTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("FTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("CFPTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("CFTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("RIbs", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("RHeat", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("RTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("ProdTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelections", New Column("chkfreezept", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffProductSelections", New Column("chkfreezetocore", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffProductSelections", New Column("fromRep", New DataTypes.YesNo))


        commands.AddTable("CoolStuffProductSelectionsReport")
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("ID", New DataTypes.AutoNumber))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("ProjectID", New DataTypes.LongInteger))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("MYID", New DataTypes.LongInteger))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("Product", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("Type", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("FreezePt", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("CHeat", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("CFHeat", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("FLatent", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("CIbs", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("CLoad", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("CPull", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("CEnter", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("CFinal", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("CTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("FTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("CFPTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("CFTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("RIbs", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("RHeat", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("RTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("ProdTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("chkfreezept", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("chkfreezetocore", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffProductSelectionsReport", New Column("fromrep", New DataTypes.YesNo))




        commands.AddTable("CoolStuffUserAshrae")
        commands.AddColumn("CoolStuffUserAshrae", New Column("Category", New DataTypes.Text))
        commands.AddColumn("CoolStuffUserAshrae", New Column("Commodity", New DataTypes.Text))
        commands.AddColumn("CoolStuffUserAshrae", New Column("Type", New DataTypes.Text))
        commands.AddColumn("CoolStuffUserAshrae", New Column("StorageTemp", New DataTypes.Text))
        commands.AddColumn("CoolStuffUserAshrae", New Column("RH", New DataTypes.Text))
        commands.AddColumn("CoolStuffUserAshrae", New Column("StorageLife", New DataTypes.Text))
        commands.AddColumn("CoolStuffUserAshrae", New Column("WaterContentpcent", New DataTypes.Double))
        commands.AddColumn("CoolStuffUserAshrae", New Column("HighFreeze", New DataTypes.Double))
        commands.AddColumn("CoolStuffUserAshrae", New Column("HeatAboveBTU", New DataTypes.Double))
        commands.AddColumn("CoolStuffUserAshrae", New Column("HeatBelowBTU", New DataTypes.Double))
        commands.AddColumn("CoolStuffUserAshrae", New Column("LatentHeatBTU", New DataTypes.Double))
        commands.AddColumn("CoolStuffUserAshrae", New Column("HeatRespire", New DataTypes.Double))
        commands.AddColumn("CoolStuffUserAshrae", New Column("FromRep", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffUserAshrae", New Column("mycounter", New DataTypes.AutoNumber))



        commands.AddTable("CoolStuffReportProject")
        commands.AddColumn("CoolStuffReportProject", New Column("ID", New DataTypes.AutoNumber))
        commands.AddColumn("CoolStuffReportProject", New Column("PROJECTID", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("REVISION", New DataTypes.LongInteger))
        commands.AddColumn("CoolStuffReportProject", New Column("Ambient", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ExtWB", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("RmTemp", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("RMWB", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("roomVolume", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("roomArea", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("Height", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ExtTempW1", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ExtTempW2", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ExtTempW3", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ExtTempW4", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ExtTempW5", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ExtTempW6", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("InsulW1", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("InsulW2", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("InsulW3", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("InsulW4", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("InsulW5", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("InsulW6", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ThickW1", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ThickW2", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ThickW3", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ThickW4", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ThickW5", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ThickW6", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("KFactorW1", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("KFactorW2", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("KFactorW3", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("KFactorW4", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("KFactorW5", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("KFactorW6", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("Walltot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("FExtTemp", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("InsulF", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ThickF", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("KFactorF", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("FloorTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("CExtTemp", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("InsulC", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ThickC", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("KFactorC", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("CeilingTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("TransTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("IVolume", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("InfWB", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("InfDB", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("IFactor", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("IAirChg", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("IHeatRem", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("TotInfil", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("Product", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("Type", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("FreezePt", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("CHeat", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("CFHeat", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("FLatent", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("CIbs", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("CLoad", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("CPull", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("CEnter", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("CFinal", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("CTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("FTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("CFPTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("CFTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("RIbs", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("RHeat", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("RTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("ProdTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("WattL", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("TotOL", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("MotorHP", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("TotOM", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("People", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("TotOP", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("OtherType", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("OtherBTU", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("TotOO", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("OtherTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("SumTran", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("SumINf", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("SumProd", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("SumOther", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("SumTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("Safety", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("SafetyTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("RunVar", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("RunVarTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("LoadTot", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("btnAllWallsy", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffReportProject", New Column("btnallwallsN", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffReportProject", New Column("chkFreezept", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffReportProject", New Column("chkfreezetoCore", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffReportProject", New Column("mystate", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("mycity", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("rw1", New DataTypes.Single))
        commands.AddColumn("CoolStuffReportProject", New Column("rw2", New DataTypes.Single))
        commands.AddColumn("CoolStuffReportProject", New Column("rw3", New DataTypes.Single))
        commands.AddColumn("CoolStuffReportProject", New Column("rw4", New DataTypes.Single))
        commands.AddColumn("CoolStuffReportProject", New Column("rw5", New DataTypes.Single))
        commands.AddColumn("CoolStuffReportProject", New Column("rw6", New DataTypes.Single))
        commands.AddColumn("CoolStuffReportProject", New Column("rwfloor", New DataTypes.Single))
        commands.AddColumn("CoolStuffReportProject", New Column("rwceiling", New DataTypes.Single))
        commands.AddColumn("CoolStuffReportProject", New Column("kfactors", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffReportProject", New Column("forklift", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("totforklift", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("dockdoors", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("totdockdoors", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("wall1", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("wall2", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("wall3", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("wall4", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("wall5", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("wall6", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("height1", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("height2", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("height3", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("height4", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("height5", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("height6", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("rdorectangle", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffReportProject", New Column("txtimagecounter", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("Description", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("UserCapacity", New DataTypes.Text))
        commands.AddColumn("CoolStuffReportProject", New Column("UserCapacityChecked", New DataTypes.YesNo))
        commands.AddColumn("CoolStuffReportProject", New Column("CreatedWhen", New DataTypes.DateTime))

    End Sub

    Public Overrides ReadOnly Property ReleaseDate() As Date
        Get
            Return #10/1/2007#
        End Get
    End Property

    Public Overrides ReadOnly Property Version() As Deployment.Version
        Get
            Return New Deployment.Version(1, 6, 0, 0)

        End Get
    End Property
End Class
